/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modul9_10;


import dao.FolderDAO;
import dao.FolderDaoSQLite;
import dao.PasswordStoreDAO;
import dao.PasswordStoreDaoSQLite;
import dao.UserDAO;
import dao.UserDaoSQLite;
import entities.Folder;
import entities.PasswordStore;
import entities.UserData;
import java.util.ArrayList;


public class App {
    public static void main(String[] args) {
        
        
        
        SetupDB.setup();
        UserDAO userDao = new UserDaoSQLite();
        FolderDAO folderDao = new FolderDaoSQLite();
        PasswordStoreDAO passwordDao = new PasswordStoreDaoSQLite();
        
        int userId1 = userDao.register("user1", "password1", "Raditya");
        int userId2 = userDao.register("user2", "password2", "Abdul");
        
        int folderId1 = folderDao.createFolder("Work");
        int folderId2 = folderDao.createFolder("Personal");
        int folderId3 = folderDao.createFolder("Finance");
        int folderId4 = folderDao.createFolder("Others");
        
        UserData user1 = userDao.login("user1", "password1");
        UserData user2 = userDao.login("user2", "password2");

        Folder folder1 = new Folder(folderId1, "Work");
        Folder folder2 = new Folder(folderId2, "Personal");
        Folder folder3 = new Folder(folderId3, "Finance");
        Folder folder4 = new Folder(folderId4, "Others");
        
        passwordDao.addPassword(new PasswordStore("Gmail", "user1@gmail.com", "password1", PasswordStore.CAT_WEBAPP, folder1), user1);
        passwordDao.addPassword(new PasswordStore("Facebook", "user1", "password2", PasswordStore.CAT_WEBAPP, folder2), user1);
        passwordDao.addPassword(new PasswordStore("Twitter", "user1", "password3", PasswordStore.CAT_WEBAPP, folder3), user1);
        passwordDao.addPassword(new PasswordStore("LinkedIn", "user1", "password4", PasswordStore.CAT_WEBAPP, folder4), user1);
        passwordDao.addPassword(new PasswordStore("GitHub", "user1", "password5", PasswordStore.CAT_WEBAPP, folder1), user1);
        
        passwordDao.addPassword(new PasswordStore("Gmail", "user2@gmail.com", "password6", PasswordStore.CAT_WEBAPP, folder2), user2);
        passwordDao.addPassword(new PasswordStore("Facebook", "user2", "password7", PasswordStore.CAT_WEBAPP, folder3), user2);
        passwordDao.addPassword(new PasswordStore("Twitter", "user2", "password8", PasswordStore.CAT_WEBAPP, folder4), user2);
        passwordDao.addPassword(new PasswordStore("LinkedIn", "user2", "password9", PasswordStore.CAT_WEBAPP, folder1), user2);
        passwordDao.addPassword(new PasswordStore("GitHub", "user2", "password10", PasswordStore.CAT_WEBAPP, folder2), user2);

        ArrayList<PasswordStore> passwords = passwordDao.listPassword(user1);
        
        System.out.println("Data Password untuk " + user1.fullname + ":");
        for (PasswordStore password : passwords) {
            System.out.println("Nama Akun: " + password.name);
            System.out.println("Username: " + password.username);
            System.out.println("Nama Kategori: " + password.getCategory());
            System.out.println("Nama Folder: " + (password.folder != null ? password.folder.name : "Tidak ada folder"));
            System.out.println("---------------------------------");
        }
        
    }
}
