/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modul_3;

import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {
   
    public static void main(String[] args) {
        /*
        try {
            String hashkey = Encryptor.generateKey();
            String plainPass = "KodeRahasiaNegara";
            String encryptedPass = Encryptor.encrypt(plainPass, hashkey);
            System.out.println("Pass (Encrypted): " + Encryptor.encrypt(encryptedPass, hashkey));
            System.out.println("Pass (Decrypted): " + Encryptor.decrypt(encryptedPass, hashkey) + "\n");

            PasswordStore pass1;
            pass1 = new PasswordStore("Akun Steam", "Raditya Abdul", "radityaabdul12345");
            pass1.setCategory(PasswordStore.CAT_WEBAPP);
            System.out.println(pass1);
            System.out.println("USERNAME: " + pass1.username + "\n" + "PASSWORD: " + pass1.getPassword());
        } catch (NoSuchAlgorithmException ex) {
            System.err.println("!!!ERROR!!!");
            System.err.println("Info: " + ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }

}
