/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uas_travel_a11202214203;

import DB.DBConnect;
import DAO.AkunDAO;
import DAO.PemesananDAO;
import DAO.PerjalananDAO;
import DB.DBSetup;
import Entitas.Akun;
import Entitas.Pemesanan;
import Entitas.Perjalanan;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

public class App {
    public static void main(String[] args) {
        
        try {
            DBSetup.createTables();
            DBConnect.connect();
            System.out.println("Koneksi database berhasil.");
        } catch (SQLException e) {
            System.err.println("Error koneksi database: " + e.getMessage());
        }
        
        LoginFrame loginFrame = new LoginFrame();
        
        
        
    }
    
}
