/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UTS_Perpustakaan;

public class App {
   
    /**
     * @param args the command line arguments
     */

    public static void main(String[] args) {
        Pustakawan pust = new Pustakawan();
        pust.logIn("A112214203", "Raditya Abdul");
        pust.inputAnggota("A12223", "Raditya Abdul Afeef", "081-529531471");
        pust.inputAnggota("A12223", "Frida Pengen Dimengerti", "081-2223334");
        pust.inputAnggota("A22334", "Fajri Hidup Sehat", "081-2223334");
        pust.inputKoleksi("Memasak Cepat Sekali", "Koki Hebat", 3);
        pust.inputKoleksi("Pemrograman Java", "Wiratno Utomo", 5);
        pust.inputKoleksi("Manajemen Admin Odoo", "Budi Andito", 2);
        pust.inputKoleksi("ERP Mudah dengan Odoo", "Waskito Hartoyo", 4);
        
        pust.cetakListAnggota();
        System.out.println("");
        pust.cetakListKoleksi();
        
        pust.signOut();
        System.out.println("");
        pust.inputAnggota("X12312", "Inputan terlarang", "000");
        System.out.println("");
        pust.inputKoleksi("Mencegah Input Terlarang", "Larang", 0);
        
    }
}
